### ISSUE TITLE
When create new product an error has occurred.

### ISSUE THREAD

**Issue by lzqwebsoft** [webgriffe/Webgriffe_Multiwarehouse#1]
When I choose to create default and simple product.then click next button an error has occurred, like this:
![non-object](https://cloud.githubusercontent.com/assets/1137657/6817444/61ad6f7e-d2db-11e4-935a-57e053423fce.png)
That said you can't check the $this->getProduct()->getStockItem() be null:
![checked](https://cloud.githubusercontent.com/assets/1137657/6817453/804ded00-d2db-11e4-8029-c5316b9cae77.png)
File Is: community\Webgriffe\Multiwarehouse\Block\Adminhtml\Qty.php
So I Changed:
![changed](https://cloud.githubusercontent.com/assets/1137657/6817475/ce30e9f0-d2db-11e4-8c57-49139d4089f1.png)

Then anything be Ok:
![multiple](https://cloud.githubusercontent.com/assets/1137657/6817482/efdff078-d2db-11e4-94ee-ad5f8441af40.png)

Thank you, This multi-warehouse plugin is great!

**Comment by lzqwebsoft** [comment]
Has another error occurred, When I create new product, and entry qty for different warehouse, then chick save button, like this:
![constraint](https://cloud.githubusercontent.com/assets/1137657/6819340/93905d0c-d2fa-11e4-8b0d-66aaee3891d0.png)
which meaning the product_id is invalid. I try to logout the value: $product->getId(), which output null.
This error has occurred is because of your listening the catalog_product_save_before event. In there you cannot get the new product id before saving.
So I change the config.xml for listening custom event : adminhtml_product_save_after:
![custom_event](https://cloud.githubusercontent.com/assets/1137657/6819401/92fbf2f6-d2fb-11e4-98b8-ee392eb23411.png)
And change core controller:Mage_Adminhtml_Catalog_ProductController:
![core_controller](https://cloud.githubusercontent.com/assets/1137657/6819412/be22fb14-d2fb-11e4-85f8-f65e533577b9.png)
Last updated the method handleMultipleQuantitiesPost() in Webgriffe_Multiwarehouse_Model_Observer:
![stock_item](https://cloud.githubusercontent.com/assets/1137657/6819433/02ca3be2-d2fc-11e4-818a-eaac4bf390c3.png)

Hope you can understand,My English is poor.

**Comment by lzqwebsoft** [comment]
My Magento version is 1.9.0.1.

**Comment by aleron75** [comment]
Hi lzqwebsoft, thank you for spotting out some issues.
We will address them and give you a response as soon as possible.

**Comment by aleron75** [comment]
Hi,
I've fixed and pushed the issues as you indicated, thank you!
