### ISSUE TITLE
Magento Warehouse

### ISSUE THREAD

**Issue by gianadrias** [webgriffe/Webgriffe_Multiwarehouse#2]
I've been installed this extension whenever i go in Manage Warehouse there nothing to show. and i follow the paths included in your readme.md
![warehouse](https://cloud.githubusercontent.com/assets/11287662/9347196/0ccd07a2-4659-11e5-8cb4-1178f62099cf.png)

**Comment by aleron75** [comment]
Can you provide some more details please?
Which version of Magento are you using?
Did you refresh the cache?
Do you use compilation? If so, did you refresh it?

**Comment by gianadrias** [comment]
• After I paste the package whenever i go to Catalog > Manage Warehouse, page is always blank. as you can see the above picture.
• done refreshing in cache and also index management.
• When i enable the compilation. Accessing Catalog > Manage Products it seems there`s a database or table error. 
Magento version 1.9.2.1

**Comment by aleron75** [comment]
> When i enable the compilation

you have to compile or re-compile before enabling compilation; I suggest you to disable compilation at all for a moment and try to understand if the problem persists; same for cache: disable all caches and try to figure out if the problem persists; are you trying the extension on a Magento vanilla or on a customized installation?
