### ISSUE TITLE
Does the extension use the native column stock_id?

### ISSUE THREAD

**Issue by seansan** [webgriffe/Webgriffe_Multiwarehouse#5]
Does the extension use the native column stock_id?

I have the idea stock is now stored in a new table, hereby excluding any stock importers/tools that rely on the default Magento tables and the already existing stock_id (or is the stock_id linked to the warehouse_id in the products table?)

**Comment by mmenozzi** [comment]
Dear @seansan,
as far as I know the Webgriffe_Multiwarehouse extension doesn't use the native stock_id column but a custom "Warehouse" entity which is linked to the product.
